apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kyc-admin-portal
  name: kyc-admin-portal
  namespace: kyc-admin
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: kyc-admin-portal
  type: ClusterIP
status:
  loadBalancer: {}
